# Generated by Django 2.2.4 on 2019-08-16 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('Health', 'health'), ('Education', 'edu'), ('Sports', 'sports'), ('Politics', 'politics'), ('Social', 'social')], default='Education', max_length=40)),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('editor', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('Health', 'health'), ('Education', 'edu'), ('Sports', 'sports'), ('Politics', 'politics'), ('Social', 'social')], default='Education', max_length=40)),
                ('content', models.FileField(upload_to='profile_pics', verbose_name='content')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
